import type { IconType } from 'react-icons';
import {
  SiAngular,
  SiBootstrap,
  SiCss,
  SiDbeaver,
  SiDocker,
  SiExpress,
  SiFastapi,
  SiFirebase,
  SiGithub,
  SiGithubpages,
  SiGitlab,
  SiGooglecolab,
  SiHostinger,
  SiHtml5,
  SiJavascript,
  SiMongodb,
  SiMysql,
  SiNodedotjs,
  SiPostgresql,
  SiPostman,
  SiPython,
  SiReact,
  SiRender,
  SiSpring,
  SiSpringboot,
  SiSwagger,
  SiTypescript,
  SiVercel,
} from 'react-icons/si';
import { TbApi, TbBrain, TbBrandVscode, TbRobot, TbSparkles, TbSql } from 'react-icons/tb';

/**
 * Brand logo + colour for each skill name in `data.skills`.
 * A missing colour means the logo follows the text colour (for black/white brand marks).
 */
export const skillIcons: Record<string, { icon: IconType; color?: string }> = {
  React: { icon: SiReact, color: '#61DAFB' },
  Angular: { icon: SiAngular, color: '#DD0031' },
  HTML5: { icon: SiHtml5, color: '#E34F26' },
  JavaScript: { icon: SiJavascript, color: '#F7DF1E' },
  TypeScript: { icon: SiTypescript, color: '#3178C6' },
  CSS3: { icon: SiCss, color: '#1572B6' },
  'Bootstrap 5': { icon: SiBootstrap, color: '#7952B3' },
  'Spring Boot (Java)': { icon: SiSpringboot, color: '#6DB33F' },
  'Node.js': { icon: SiNodedotjs, color: '#5FA04E' },
  'Express.js': { icon: SiExpress },
  'REST APIs': { icon: TbApi },
  MySQL: { icon: SiMysql, color: '#4479A1' },
  MongoDB: { icon: SiMongodb, color: '#47A248' },
  PostgreSQL: { icon: SiPostgresql, color: '#4169E1' },
  Python: { icon: SiPython, color: '#3776AB' },
  FastAPI: { icon: SiFastapi, color: '#009688' },
  'LLM Fine-tuning (LoRA)': { icon: TbBrain },
  'Text-to-SQL': { icon: TbSql },
  'Google Colab': { icon: SiGooglecolab, color: '#F9AB00' },
  'AI Agents & Workflows': { icon: TbRobot },
  'Vibe Coding (AI-assisted dev)': { icon: TbSparkles },
  Docker: { icon: SiDocker, color: '#2496ED' },
  GitLab: { icon: SiGitlab, color: '#FC6D26' },
  GitHub: { icon: SiGithub },
  Postman: { icon: SiPostman, color: '#FF6C37' },
  Swagger: { icon: SiSwagger, color: '#85EA2D' },
  'VS Code': { icon: TbBrandVscode, color: '#007ACC' },
  'Spring Tool Suite': { icon: SiSpring, color: '#6DB33F' },
  DBeaver: { icon: SiDbeaver, color: '#9B6D4B' },
  Firebase: { icon: SiFirebase, color: '#FFCA28' },
  'GitHub Pages': { icon: SiGithubpages },
  Vercel: { icon: SiVercel },
  Render: { icon: SiRender },
  'Hostinger VPS': { icon: SiHostinger, color: '#673DE6' },
};
